### ISSUE TITLE
requests.exceptions.MissingSchema while using the API

### ISSUE THREAD

**Issue by bpinaya** [superannotateai/superannotate-python-sdk#528]
Using the code to prepare an export:
```python
from superannotate import SAClient

sa = SAClient(config_path="~/.superannotate/config.json")

project_name = 'Demo_dataset'  #include folder name if images are in folder
save_directory = 'DIRECTORYHERE'

project_export = sa.prepare_export(project=project_name,
                                   annotation_statuses=["Completed"])

```
I am having the following output:
```
SA-PYTHON-SDK - WARNING - There is a newer version of SuperAnnotate Python SDK available on PyPI. Run 'pip install --upgrade superannotate' to upgrade from your version 4.4.0 to 4.4.5
Traceback (most recent call last):
  File "sa_handling.py", line 14, in <module>
    annotation_statuses = ["Completed"])
  File "/home/PIB1TI/anaconda3/envs/torchinf/lib/python3.6/site-packages/superannotate/lib/app/interface/base_interface.py", line 173, in __call__
    raise e
  File "/home/PIB1TI/anaconda3/envs/torchinf/lib/python3.6/site-packages/superannotate/lib/app/interface/base_interface.py", line 170, in __call__
    result = self.function(*args, **kwargs)
  File "/home/PIB1TI/anaconda3/envs/torchinf/lib/python3.6/site-packages/superannotate/lib/app/interface/types.py", line 188, in wrapped
    return pydantic_validate_arguments(func)(self, *args, **kwargs)
  File "pydantic/decorator.py", line 40, in pydantic.decorator.validate_arguments.validate.wrapper_function
    import itertools
  File "pydantic/decorator.py", line 134, in pydantic.decorator.ValidatedFunction.call
    if doc:
  File "pydantic/decorator.py", line 201, in pydantic.decorator.ValidatedFunction.execute
    evaldict is the evaluation dictionary. If addsource is true an
  File "/home/PIB1TI/anaconda3/envs/torchinf/lib/python3.6/site-packages/superannotate/lib/app/interface/sdk_interface.py", line 1109, in prepare_export
    annotation_statuses=annotation_statuses,
  File "/home/PIB1TI/anaconda3/envs/torchinf/lib/python3.6/site-packages/superannotate/lib/infrastructure/controller.py", line 519, in prepare_export
    project = self._get_project(project_name)
  File "/home/PIB1TI/anaconda3/envs/torchinf/lib/python3.6/site-packages/superannotate/lib/infrastructure/controller.py", line 209, in _get_project
    response = use_case.execute()
  File "/home/PIB1TI/anaconda3/envs/torchinf/lib/python3.6/site-packages/superannotate/lib/core/usecases/projects.py", line 69, in execute
    projects = self._projects.get_all(condition)
  File "/home/PIB1TI/anaconda3/envs/torchinf/lib/python3.6/site-packages/superannotate/lib/infrastructure/repositories.py", line 97, in get_all
    return parse_obj_as(List[ProjectEntity], self._service.get_projects(condition))
  File "/home/PIB1TI/anaconda3/envs/torchinf/lib/python3.6/site-packages/superannotate/lib/infrastructure/services.py", line 334, in get_projects
    data = self._get_all_pages(url)
  File "/home/PIB1TI/anaconda3/envs/torchinf/lib/python3.6/site-packages/superannotate/lib/infrastructure/services.py", line 178, in _get_all_pages
    resources, remains_count = self._get_page(url, offset, params, key_field)
  File "/home/PIB1TI/anaconda3/envs/torchinf/lib/python3.6/site-packages/superannotate/lib/infrastructure/services.py", line 157, in _get_page
    response = self._request(url, params=params)
  File "/home/PIB1TI/anaconda3/envs/torchinf/lib/python3.6/site-packages/superannotate/lib/infrastructure/services.py", line 133, in _request
    prepared = session.prepare_request(req)
  File "/home/PIB1TI/anaconda3/envs/torchinf/lib/python3.6/site-packages/requests/sessions.py", line 466, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "/home/PIB1TI/anaconda3/envs/torchinf/lib/python3.6/site-packages/requests/models.py", line 316, in prepare
    self.prepare_url(url, params)
  File "/home/PIB1TI/anaconda3/envs/torchinf/lib/python3.6/site-packages/requests/models.py", line 390, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL 'projects?name=Demo_dataset&team_id=15841&offset=0': No schema supplied. Perhaps you meant http://projects?name=Demo_dataset&team_id=15841&offset=0?
```
I am having similar issues while testing other functions of the API.
Any hints are appreciated.

**Comment by VaghinakDev** [comment]
Hi,  @bpinaya thanks for reaching out. I guess they might be invalid config.json, please try with the latest version of the SDK 4.4.5

**Comment by bpinaya** [comment]
Pip installs 4.4.0 on Python  in conda `Python 3.6.10 :: Anaconda, Inc.` btw
```
superannotate             4.4.0                    pypi_0    pypi
```
Trying:
```
pip install superannotate==4.4.5
```
gives:
```
ERROR: Could not find a version that satisfies the requirement superannotate==4.4.5 (from versions: 1.5.6, 1.5.7, 1.5.8, 1.5.9, 1.5.10, 1.5.11, 1.5.13, 1.6.0, 1.6.1, 1.6.3, 1.6.4, 1.7.0, 1.7.1, 1.7.2, 1.8.0, 1.9.0, 1.9.1, 1.9.2, 1.9.3, 1.9.4, 1.9.5, 1.9.6, 1.9.7, 1.9.8, 1.9.9, 1.9.10, 2.0.0, 2.0.1, 2.0.2, 2.0.3, 2.0.4, 2.1.0, 2.1.1, 2.1.2, 2.1.3, 2.1.4, 2.1.5, 2.2.0, 2.2.1, 2.2.2, 2.2.3, 2.2.4, 2.2.5, 2.2.6, 2.3.0, 2.3.1, 2.3.2, 2.3.5, 2.3.6, 2.3.7, 2.3.8, 2.3.9, 2.3.10, 2.3.11, 2.3.12, 2.3.13, 2.3.15, 2.3.16, 2.3.18, 2.3.19, 2.3.20, 2.4.0b1, 2.4.0b2, 2.4.0b3, 2.4.0b4, 2.4.0b5, 2.4.0b6, 2.4.0, 2.4.1, 2.4.2, 2.5.0b0, 2.5.0b2, 2.5.0b3, 2.5.0b4, 2.5.0b5, 2.5.0b7, 2.5.0b10, 2.5.0b11, 2.5.0b12, 2.5.0b13, 2.5.0b14, 2.5.0b15, 2.5.0b16, 2.5.0b17, 2.5.0b18, 2.5.1, 2.5.2b0, 2.5.2b2, 2.5.2b3, 2.5.2b4, 2.5.2b8, 2.5.2, 2.5.4, 2.5.5b1, 2.5.5b2, 2.5.6, 2.5.7, 2.5.8, 2.5.9, 2.5.11, 2.5.12, 3.0.0b1, 3.0.0b2, 3.0.0b3, 3.0.0b5, 3.0.0b6, 3.0.0b20, 3.0.0, 3.0.2, 3.1.0, 3.1.1, 3.1.2, 3.1.3, 3.2.0, 3.2.2, 3.2.3, 3.2.4, 3.2.5, 3.2.6, 4.0.0b1, 4.0.0b2, 4.0.0, 4.0.1, 4.1.0b1, 4.1.0b2, 4.1.0b3, 4.1.0b5, 4.1.0b6, 4.1.0b7, 4.1.0b8, 4.1.0b9, 4.1.0b10, 4.1.0b11, 4.1.0b12, 4.1.0b13, 4.1.0b14, 4.1.0b15, 4.1.0b16, 4.1.0b17, 4.1.0b18, 4.1.0, 4.1.1b1, 4.1.1b2, 4.1.1b3, 4.1.1b4, 4.1.1b5, 4.1.1b6, 4.1.1, 4.1.2b1, 4.1.2b2, 4.1.2b3, 4.1.2, 4.1.3b1, 4.1.3b2, 4.1.3b3, 4.1.3b4, 4.1.3b5, 4.1.3b6, 4.1.3b7, 4.1.3, 4.1.4b1, 4.1.4b3, 4.1.4b4, 4.1.4b5, 4.1.4b6, 4.1.4b7, 4.1.4, 4.1.5b1, 4.1.5b2, 4.1.5b3, 4.1.5b4, 4.1.5b5, 4.1.5b6, 4.1.5b7, 4.1.5b8, 4.1.5b9, 4.1.5b11, 4.1.5, 4.1.6b1, 4.1.6b2, 4.1.6b3, 4.1.6b4, 4.1.6, 4.1.7b1, 4.1.7b3, 4.1.7b4, 4.1.7, 4.1.8b1, 4.1.8b2, 4.1.8b3, 4.1.8, 4.1.9, 4.2.0, 4.2.1, 4.2.2b1, 4.2.2, 4.2.3b1, 4.2.3b2, 4.2.3b3, 4.2.3b4, 4.2.3b5, 4.2.3b6, 4.2.3b7, 4.2.3, 4.2.4b1, 4.2.4b2, 4.2.4, 4.2.5b1, 4.2.5b2, 4.2.5b3, 4.2.5b4, 4.2.5b5, 4.2.5b6, 4.2.5b8, 4.2.5b9, 4.2.5b10, 4.2.6, 4.2.7b1, 4.2.7b2, 4.2.7b3, 4.2.7b4, 4.2.7b5, 4.2.7b6, 4.2.7, 4.2.8b1, 4.2.8b3, 4.2.8b5, 4.2.8b6, 4.2.8b7, 4.2.8b8, 4.2.8b9, 4.2.8b10, 4.2.8b11, 4.2.8b12, 4.2.8b13, 4.2.8b14, 4.2.8b15, 4.2.8, 4.2.9b1, 4.2.9b2, 4.2.9b3, 4.2.9b4, 4.2.9b5, 4.2.9b6, 4.2.9, 4.3.0.dev1, 4.3.0.dev2, 4.3.0.dev4, 4.3.0.dev5, 4.3.0.dev6, 4.3.0.dev7, 4.3.0.dev9, 4.3.0.dev10, 4.3.0.dev11, 4.3.0.dev13, 4.3.0.dev14, 4.3.0.dev16, 4.3.0.dev17, 4.3.0.dev18, 4.3.0.dev19, 4.3.0.dev20, 4.3.0.dev21, 4.3.0b1, 4.3.0b2, 4.3.0b3, 4.3.0b4, 4.3.0b5, 4.3.0b6, 4.3.0b7, 4.3.0b10, 4.3.0b11, 4.3.0b12, 4.3.0b13, 4.3.0b14, 4.3.0b15, 4.3.0b16, 4.3.0b17, 4.3.0b18, 4.3.0b19, 4.3.0b20, 4.3.0, 4.3.1b2, 4.3.1b3, 4.3.1, 4.3.2.dev1, 4.3.2.dev2, 4.3.2.dev3, 4.3.2.dev4, 4.3.2.dev5, 4.3.2.dev6, 4.3.2.dev7, 4.3.2.dev8, 4.3.2.dev9, 4.3.2b1, 4.3.2b3, 4.3.2b4, 4.3.2b5, 4.3.2b6, 4.3.2b7, 4.3.2, 4.3.3.dev1, 4.3.3.dev11, 4.3.3.dev12, 4.3.3b1, 4.3.3b2, 4.3.3b5, 4.3.3, 4.3.4.dev1, 4.3.4.dev2, 4.3.4.dev3, 4.3.4.dev4, 4.3.4b1, 4.3.4b2, 4.3.4b3, 4.3.4, 4.3.5.dev1, 4.3.5.dev2, 4.3.5.dev11, 4.3.5.dev12, 4.3.5.dev13, 4.3.5.dev14, 4.3.5.dev15, 4.3.5.dev16, 4.3.5.dev17, 4.3.5.dev18, 4.3.5.dev20, 4.3.5.dev21, 4.3.5.dev22, 4.3.5.dev23, 4.3.5b1, 4.4.0, 4.4.1.dev2, 4.4.1.dev3, 4.4.1.dev4, 4.4.1.dev5, 4.4.1.dev6, 4.4.1.dev7, 4.4.1.dev8)
ERROR: No matching distribution found for superannotate==4.4.5
```
Trying to update in python 3.6 also doesn't work `pip install --upgrade superannotate` doesn't upgrade it. I could try building from source but under Python 3.9.12 it seems to work:
```
superannotate             4.4.5                    pypi_0    pypi
```
and indeed that fixes the issue, note that the readme might need to be updated as this part says:
```
The package officially supports Python 3.6+ and was tested under Linux and Windows ([Anaconda](https://www.anaconda.com/products/individual#windows)) platforms.
```
